[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.3.4",
    "ollama>=0.6.0",
    "openai>=2.5.0",
    "pandas>=2.3.3",
    "streamlit>=1.50.0",
]
